# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f18308864ec3d65385b20388963c2cf9c98c89558d4db5354705f967c7481b80abf2a9f6ec65287e064726894e067f71ba5edc9fdf970c8e7d21685239f5b27

test:
  secret_key_base: dd637651b0e5d30ea9327aaffa2cdba57efc829e30e2889ff89fd4ab0f89da499ecf39d7c2b566d8f505490aa860b5b49ea0c5e294acecfe1a017d8a6310b2cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
